FROM mysql:8.0.12
RUN echo "Asia/Tokyo" > /etc/timezone
RUN dpkg-reconfigure -f noninteractive tzdata
ENV LANG ja_JP.UTF-8
ENV MYSQL_ROOT_PASSWORD rootpasswd
ENV TZ 'Asia/Tokyo'
ENV TERM 'xterm'
EXPOSE 3306
ADD my.cnf /etc/mysql/conf.d/my.cnf
ADD ./files/init/*.sql /docker-entrypoint-initdb.d